In [1]:
# Import necessary libraries
import os
import zipfile
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models

In [2]:

# Extract the dataset
with zipfile.ZipFile("GestRepo.zip", 'r') as zip_ref:
    zip_ref.extractall("hand_gestures_dataset")

# Define the paths to your dataset
dataset_dir = 'hand_gestures_dataset'

In [3]:
# Data preprocessing and augmentation
datagen = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

In [8]:

# Load and augment the dataset
image_size = (128, 128)
batch_size = 32




# Load and augment the dataset
image_size = (128, 128)
batch_size = 32

train_generator = datagen.flow_from_directory(
    os.path.join(dataset_dir),
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

test_generator = datagen.flow_from_directory(
    os.path.join(dataset_dir),
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

Found 40000 images belonging to 1 classes.
Found 40000 images belonging to 1 classes.


In [10]:

# Build the CNN model
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))



In [11]:
# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
# Train the model
model.fit(train_generator, epochs=10, validation_data=test_generator)

Epoch 1/10


1250/1250 [==============================] - 1460s 1s/step - loss: 787.3994 - accuracy: 0.0854 - val_loss: 786.3710 - val_accuracy: 0.0967
Epoch 2/10
1250/1250 [==============================] - 1888s 2s/step - loss: 786.3710 - accuracy: 0.0801 - val_loss: 786.3708 - val_accuracy: 0.0688
Epoch 3/10
1250/1250 [==============================] - 40158s 32s/step - loss: 761.0317 - accuracy: 0.0968 - val_loss: 755.1918 - val_accuracy: 0.0227
Epoch 4/10
1250/1250 [==============================] - 2558s 2s/step - loss: 755.1918 - accuracy: 0.0279 - val_loss: 755.1918 - val_accuracy: 0.0024
Epoch 5/10
1250/1250 [==============================] - 4342s 3s/step - loss: 755.1918 - accuracy: 0.0111 - val_loss: 755.1918 - val_accuracy: 0.0360
Epoch 6/10
1250/1250 [==============================] - 1258s 1s/step - loss: 755.1918 - accuracy: 0.0057 - val_loss: 755.1918 - val_accuracy: 0.0033
Epoch 7/10
1250/1250 [==============================] - 787s 629ms/step - loss: 755.1918 - accur

In [16]:

# Evaluate the model and print confusion matrix
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Generate predictions
Y_pred = model.predict(test_generator)
y_pred = np.argmax(Y_pred, axis=1)  # Assuming the model output is one-hot encoded

# Get true labels
y_true = test_generator.classes

# Print confusion matrix and classification report
conf_matrix = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

class_report = classification_report(y_true, y_pred, labels=np.unique(y_true))
print("\nClassification Report:")
print(class_report)


1250/1250 [==============================] - 495s 396ms/step
Confusion Matrix:
[[ 168    6   21 ...   13 1560   18]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.00      0.01     40000

   micro avg       1.00      0.00      0.01     40000
   macro avg       1.00      0.00      0.01     40000
weighted avg       1.00      0.00      0.01     40000

